ESPICOURTS/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm, \
    password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', login, {'template_name': 'log/login.html'}, name="login"),
    url(r'^accounts/login', login, {'template_name': 'log/login.html'}, name="login"),
    url(r'^salir$', logout, name="salir", kwargs={'next_page': '/'}),
    url(r'^reset/password_reset', password_reset, {'template_name': 'log/password_reset_form.html',
                                                   'email_template_name': 'log/password_reset_email.html'},
                                                    name="password_reset"),
    url(r'^password_reset_done', password_reset_done, {'template_name': 'log/password_reset_done.html'},
                                                        name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-94-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'log/password_reset_confirm.html'}, name="password_reset_confirm"),
    url(r'^reset/done', password_reset_complete, {'template_name': 'log/password_reset_complete.html'},
        name="password_reset_complete"),
    url(r'^espicourts/', include('apps.inicio.urls', namespace='espicourts')),

]

apps/inicio/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from apps.inicio.views import DetalleCancha, ListarCancha, CrearCancha, EditarCancha, EliminarCancha, DetalleEquipo, \
    ListarEquipo, CrearEquipo, EditarEquipo, EliminarEquipo, CrearPartido, DetallePartido, ListarPartido, \
    EliminarPartido, EditarPartido, CrearUsuario, DetalleUsuario, ListarUsuario, EliminarUsuario, EditarUsuario, \
    DetalleEvento, ListarEvento, CrearEvento, EditarEvento, EliminarEvento, DetalleJugador, ListarJugador, CrearJugador, \
    EditarJugador, EliminarJugador, DetalleTorneo, ListarTorneo, CrearTorneo, EditarTorneo, EliminarTorneo, Index, \
    DetalleTorneoPartido, CrearTorneoPartido, EditarTorneoPartido, EliminarTorneoPartido, \
    ListarReserva, CrearReserva, EliminarReserva, DetalleReserva, ListarTorneoPartido

urlpatterns = [
    url(r'^index/',Index, name='index'),
    url(r'^canchas_detalle/(?P<pk>\d+)/$',login_required(DetalleCancha.as_view()), name='canchas_detalle'),
    url(r'^canchas_listar', login_required(ListarCancha.as_view()), name='canchas_listar'),
    url(r'^canchas_crear', login_required(CrearCancha), name='canchas_crear'),
    url(r'^canchas_actualizar/(?P<id_cancha>\d+)/$', login_required(EditarCancha),name='canchas_actualizar'),
    url(r'^canchas_eliminar/(?P<pk>\d+)/$', login_required(EliminarCancha.as_view()),name='canchas_eliminar'),
    url(r'^equipos_detalle/(?P<pk>\d+)/$', login_required(DetalleEquipo.as_view()), name='equipos_detalle'),
    url(r'^equipos_listar', login_required(ListarEquipo.as_view()), name='equipos_listar'),
    url(r'^equipos_crear', login_required(CrearEquipo), name='equipos_crear'),
    url(r'^equipos_actualizar/(?P<id_equipo>\d+)/$', login_required(EditarEquipo),name='equipos_actualizar'),
    url(r'^equipos_eliminar/(?P<pk>\d+)/$', login_required(EliminarEquipo.as_view()),name='equipos_eliminar'),
    url(r'^partidos_detalle/(?P<pk>\d+)/$', login_required(DetallePartido.as_view()), name='partidos_detalle'),
    url(r'^partidos_listar', login_required(ListarPartido.as_view()), name='partidos_listar'),
    url(r'^partidos_crear', login_required(CrearPartido), name='partidos_crear'),
    url(r'^partidos_actualizar/(?P<id_partido>\d+)/$', login_required(EditarPartido),name='partidos_actualizar'),
    url(r'^partidos_eliminar/(?P<pk>\d+)/$', login_required(EliminarPartido.as_view()),name='partidos_eliminar'),
    url(r'^usuarios_detalle/(?P<pk>\d+)/$', login_required(DetalleUsuario.as_view()), name='usuario_detalle'),
    url(r'^usuarios_listar', login_required(ListarUsuario.as_view()), name='usuarios_listar'),
    url(r'^usuarios_crear', login_required(CrearUsuario), name='usuarios_crear'),
    url(r'^usuarios_actualizar/(?P<id_usuario>\d+)/$', login_required(EditarUsuario),name='usuarios_actualizar'),
    url(r'^usuarios_eliminar/(?P<pk>\d+)/$', login_required(EliminarUsuario.as_view()),name='usuarios_eliminar'),
    url(r'^eventos_detalle/(?P<pk>\d+)/$', login_required(DetalleEvento.as_view()), name='evento_detalle'),
    url(r'^eventos_listar', login_required(ListarEvento.as_view()), name='eventos_listar'),
    url(r'^eventos_crear', login_required(CrearEvento), name='eventos_crear'),
    url(r'^eventos_actualizar/(?P<id_evento>\d+)/$', login_required(EditarEvento),name='eventos_actualizar'),
    url(r'^eventos_eliminar/(?P<pk>\d+)/$', login_required(EliminarEvento.as_view()),name='eventos_eliminar'),
    url(r'^jugadores_detalle/(?P<pk>\d+)/$', login_required(DetalleJugador.as_view()), name='jugador_detalle'),
    url(r'^jugadores_listar', login_required(ListarJugador.as_view()), name='jugadores_listar'),
    url(r'^jugadores_crear', login_required(CrearJugador), name='jugadores_crear'),
    url(r'^jugadores_actualizar/(?P<id_jugador>\d+)/$', login_required(EditarJugador),name='jugadores_actualizar'),
    url(r'^jugadores_eliminar/(?P<pk>\d+)/$', login_required(EliminarJugador.as_view()),name='jugadores_eliminar'),
    url(r'^torneos_detalle/(?P<pk>\d+)/$', login_required(DetalleTorneo.as_view()), name='torneo_detalle'),
    url(r'^torneos_listar', login_required(ListarTorneo.as_view()), name='torneos_listar'),
    url(r'^torneos_crear', login_required(CrearTorneo), name='torneos_crear'),
    url(r'^torneos_actualizar/(?P<id_torneo>\d+)/$', login_required(EditarTorneo),name='torneos_actualizar'),
    url(r'^torneos_eliminar/(?P<pk>\d+)/$', login_required(EliminarTorneo.as_view()),name='torneos_eliminar'),
    url(r'^torneo_partido_detalle/(?P<pk>\d+)/$', login_required(DetalleTorneoPartido.as_view()), name='torneo_partido_detalle'),
    url(r'^torneo_partido_listar/', ListarTorneoPartido, name='torneo_partido_listar'),
    url(r'^torneo_partido_crear/(?P<id_torneo>\d+)/$', CrearTorneoPartido, name='torneo_partido_crear'),
    url(r'^torneo_partido_actualizar/(?P<id_torneop>\d+)/$', login_required(EditarTorneoPartido),name='torneo_partido_actualizar'),
    url(r'^torneo_partido_eliminar/(?P<pk>\d+)/$', login_required(EliminarTorneoPartido.as_view()),name='torneo_partido_eliminar'),
    url(r'^reservas_detalle/(?P<pk>\d+)/$', login_required(DetalleReserva.as_view()), name='reserva_detalle'),
    url(r'^reservas_listar', login_required(ListarReserva.as_view()), name='reservas_listar'),
    url(r'^reservas_crear', login_required(CrearReserva), name='reservas_crear'),
    url(r'^reservas_eliminar/(?P<pk>\d+)/$', login_required(EliminarReserva.as_view()),name='reservas_eliminar'),

]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block extrastatic %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %} ">
    <title>{%block title%} Title {% endblock %}</title>
<!--este se usa para agregar nuetros link de las distintas librerias-->

    {% block fondopantalla %}
    <style>
    html {
        height:100%;
        width:100%;
    }
    body{
        background:white url("../../static/images/cancha_sintetica.jpg") no-repeat center center;
        background-size:100% 100%;
    }
    </style>
    {% endblock %}
</head>
<body>
{% block navbar %}
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a href="{% url 'espicourts:index' %}" class="navbar-brand">
                <img src="../../static/images/espicourts-logo-mini.png" style="margin-top:-10px;"></a>
        </div>
        <ul class="nav navbar-nav navbar-static-top">
            <li><a href="{%  url 'espicourts:usuarios_listar' %}">Usuarios</a></li>
            <li><a href="{%  url 'espicourts:jugadores_listar' %}">Jugadores</a></li>
            <li><a href="{% url 'espicourts:equipos_listar' %}">Equipos</a></li>
            <li><a href="{% url 'espicourts:canchas_listar' %}">Canchas</a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Partidos <b class="caret"></b>
                </a>
                <ul class="dropdown-menu" role="menubar">
                    <li><a href="{% url 'espicourts:partidos_listar' %}">Partidos</a></li>
                    <li><a href="{% url 'espicourts:eventos_listar' %}">Eventos del partido</a></li>
                </ul>
            </li>
            <li><a href="{% url 'espicourts:torneos_listar' %}">Torneos</a></li>
            <li><a href="{% url 'espicourts:reservas_listar' %}">Reservas</a></li>
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Buscar">
                </div>
                <button type="submit" class="btn btn-default">Enviar</button>
            </form>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    {{ user.get_username }} <b class="caret"></b>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'password_reset' %}">Cambiar Contraseña</a></li>
                    <li><a href="{% url 'salir' %}">Salir</a></li>
                </ul>
             </li>
        </ul>
    </div>
</nav>
<div class="container">
{% endblock %}
<!--bloque para el header-->
    {% block header %}
    {% endblock %}
<!--bloque para el contenido que es renderizado-->
    {% block content %}
    {% endblock %}
<!--bloque para el footer-->
    {% block footer %}
    <footer class="container-fluid text-center bg-lightgray">
        <div class="copyrights" style="margin-top:25px;">
            <p>ESPICOURTS © 2017, All Rights Reserved
                <br>
                <span>Web Design By: Los propios</span></p>
        </div>
    </footer>
    {% endblock %}
<!--bloque para el las libreias extra necesarias-->
</div>
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block extrajs %}
{% endblock %}
</body>
</html>