ESPICOURTS/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm, \
    password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', login, {'template_name': 'log/login.html'}, name="login"),
    url(r'^accounts/login', login, {'template_name': 'log/login.html'}, name="login"),
    url(r'^salir$', logout, name="salir", kwargs={'next_page': '/'}),
    url(r'^reset/password_reset', password_reset, {'template_name': 'log/password_reset_form.html',
                                                   'email_template_name': 'log/password_reset_email.html'},
                                                    name="password_reset"),
    url(r'^password_reset_done', password_reset_done, {'template_name': 'log/password_reset_done.html'},
                                                        name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-94-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'log/password_reset_confirm.html'}, name="password_reset_confirm"),
    url(r'^reset/done', password_reset_complete, {'template_name': 'log/password_reset_complete.html'},
        name="password_reset_complete"),
    url(r'^espicourts/', include('apps.inicio.urls', namespace='espicourts')),

]

apps/inicio/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from apps.inicio.views import DetalleCancha, ListarCancha, CrearCancha, EditarCancha, EliminarCancha, DetalleEquipo, \
    ListarEquipo, CrearEquipo, EditarEquipo, EliminarEquipo, CrearPartido, DetallePartido, ListarPartido, \
    EliminarPartido, EditarPartido, CrearUsuario, DetalleUsuario, ListarUsuario, EliminarUsuario, EditarUsuario, \
    DetalleEvento, ListarEvento, CrearEvento, EditarEvento, EliminarEvento, DetalleJugador, ListarJugador, CrearJugador, \
    EditarJugador, EliminarJugador, DetalleTorneo, ListarTorneo, CrearTorneo, EditarTorneo, EliminarTorneo, Index, \
    DetalleTorneoPartido, CrearTorneoPartido, EditarTorneoPartido, EliminarTorneoPartido, \
    ListarReserva, CrearReserva, EliminarReserva, DetalleReserva, ListarTorneoPartido

urlpatterns = [
    url(r'^index/',Index, name='index'),
    url(r'^canchas_detalle/(?P<pk>\d+)/$',login_required(DetalleCancha.as_view()), name='canchas_detalle'),
    url(r'^canchas_listar', login_required(ListarCancha.as_view()), name='canchas_listar'),
    url(r'^canchas_crear', login_required(CrearCancha), name='canchas_crear'),
    url(r'^canchas_actualizar/(?P<id_cancha>\d+)/$', login_required(EditarCancha),name='canchas_actualizar'),
    url(r'^canchas_eliminar/(?P<pk>\d+)/$', login_required(EliminarCancha.as_view()),name='canchas_eliminar'),
    url(r'^equipos_detalle/(?P<pk>\d+)/$', login_required(DetalleEquipo.as_view()), name='equipos_detalle'),
    url(r'^equipos_listar', login_required(ListarEquipo.as_view()), name='equipos_listar'),
    url(r'^equipos_crear', login_required(CrearEquipo), name='equipos_crear'),
    url(r'^equipos_actualizar/(?P<id_equipo>\d+)/$', login_required(EditarEquipo),name='equipos_actualizar'),
    url(r'^equipos_eliminar/(?P<pk>\d+)/$', login_required(EliminarEquipo.as_view()),name='equipos_eliminar'),
    url(r'^partidos_detalle/(?P<pk>\d+)/$', login_required(DetallePartido.as_view()), name='partidos_detalle'),
    url(r'^partidos_listar', login_required(ListarPartido.as_view()), name='partidos_listar'),
    url(r'^partidos_crear', login_required(CrearPartido), name='partidos_crear'),
    url(r'^partidos_actualizar/(?P<id_partido>\d+)/$', login_required(EditarPartido),name='partidos_actualizar'),
    url(r'^partidos_eliminar/(?P<pk>\d+)/$', login_required(EliminarPartido.as_view()),name='partidos_eliminar'),
    url(r'^usuarios_detalle/(?P<pk>\d+)/$', login_required(DetalleUsuario.as_view()), name='usuario_detalle'),
    url(r'^usuarios_listar', login_required(ListarUsuario.as_view()), name='usuarios_listar'),
    url(r'^usuarios_crear', login_required(CrearUsuario), name='usuarios_crear'),
    url(r'^usuarios_actualizar/(?P<id_usuario>\d+)/$', login_required(EditarUsuario),name='usuarios_actualizar'),
    url(r'^usuarios_eliminar/(?P<pk>\d+)/$', login_required(EliminarUsuario.as_view()),name='usuarios_eliminar'),
    url(r'^eventos_detalle/(?P<pk>\d+)/$', login_required(DetalleEvento.as_view()), name='evento_detalle'),
    url(r'^eventos_listar', login_required(ListarEvento.as_view()), name='eventos_listar'),
    url(r'^eventos_crear', login_required(CrearEvento), name='eventos_crear'),
    url(r'^eventos_actualizar/(?P<id_evento>\d+)/$', login_required(EditarEvento),name='eventos_actualizar'),
    url(r'^eventos_eliminar/(?P<pk>\d+)/$', login_required(EliminarEvento.as_view()),name='eventos_eliminar'),
    url(r'^jugadores_detalle/(?P<pk>\d+)/$', login_required(DetalleJugador.as_view()), name='jugador_detalle'),
    url(r'^jugadores_listar', login_required(ListarJugador.as_view()), name='jugadores_listar'),
    url(r'^jugadores_crear', login_required(CrearJugador), name='jugadores_crear'),
    url(r'^jugadores_actualizar/(?P<id_jugador>\d+)/$', login_required(EditarJugador),name='jugadores_actualizar'),
    url(r'^jugadores_eliminar/(?P<pk>\d+)/$', login_required(EliminarJugador.as_view()),name='jugadores_eliminar'),
    url(r'^torneos_detalle/(?P<pk>\d+)/$', login_required(DetalleTorneo.as_view()), name='torneo_detalle'),
    url(r'^torneos_listar', login_required(ListarTorneo.as_view()), name='torneos_listar'),
    url(r'^torneos_crear', login_required(CrearTorneo), name='torneos_crear'),
    url(r'^torneos_actualizar/(?P<id_torneo>\d+)/$', login_required(EditarTorneo),name='torneos_actualizar'),
    url(r'^torneos_eliminar/(?P<pk>\d+)/$', login_required(EliminarTorneo.as_view()),name='torneos_eliminar'),
    url(r'^torneo_partido_detalle/(?P<pk>\d+)/$', login_required(DetalleTorneoPartido.as_view()), name='torneo_partido_detalle'),
    url(r'^torneo_partido_listar/', ListarTorneoPartido, name='torneo_partido_listar'),
    url(r'^torneo_partido_crear/(?P<id_torneo>\d+)/$', CrearTorneoPartido, name='torneo_partido_crear'),
    url(r'^torneo_partido_actualizar/(?P<id_torneop>\d+)/$', login_required(EditarTorneoPartido),name='torneo_partido_actualizar'),
    url(r'^torneo_partido_eliminar/(?P<pk>\d+)/$', login_required(EliminarTorneoPartido.as_view()),name='torneo_partido_eliminar'),
    url(r'^reservas_detalle/(?P<pk>\d+)/$', login_required(DetalleReserva.as_view()), name='reserva_detalle'),
    url(r'^reservas_listar', login_required(ListarReserva.as_view()), name='reservas_listar'),
    url(r'^reservas_crear', login_required(CrearReserva), name='reservas_crear'),
    url(r'^reservas_eliminar/(?P<pk>\d+)/$', login_required(EliminarReserva.as_view()),name='reservas_eliminar'),

]

apps/inicio/models.py
from django.contrib.auth.models import User
from django.db import models



class Equipo(models.Model):
    nombre_equipo=models.CharField('Nombre del Equipo', max_length=30)
    categorias=((1,'Categoria A'),(2,'Categoria B'),(3,'Categoria C'))
    categoria_equipo=models.SmallIntegerField(choices=categorias)
    class Meta:
        db_table='equipo'
    def __str__(self):
        return  "%s " % (self.nombre_equipo)


class Jugador(models.Model):
    identificacion=models.CharField('Identificacion',max_length=12)
    tidentificaciones=((1,'T.I'),(2,'C.C'),(3,'C.E'))
    tipo_identifcacion=models.SmallIntegerField(choices=tidentificaciones)
    edad=models.IntegerField('Edad')
    telefono=models.CharField('Telefono',max_length=20)
    perfil=models.CharField('Perfil del jugador',max_length=60)
    genero = ((1, 'Masculino'), (2, 'Femenino'))
    sexo = models.SmallIntegerField(choices=genero)
    equipo=models.ForeignKey(Equipo,null=True)
    usuario=models.OneToOneField(User, null=True)
    class Meta:
        db_table='jugador'
    def __str__(self):
        return "%s %i %i %s %s %i %i" % (self.identificacion,self.tipo_identifcacion,
                                         self.edad,self.telefono,self.perfil,self.tipo_usuario,
                                         self.sexo)
class Cancha(models.Model):
    nombre_cancha=models.CharField('Nombre', max_length=30)
    direccion_cancha = models.CharField('Direccion', max_length=60)
    class Meta:
        db_table='cancha'
    def __str__(self):
        return "%s " % (self.nombre_cancha)


class Partido(models.Model):
    fecha_partido=models.DateField()
    hora_inicio=models.TimeField()
    hora_fin = models.TimeField(null=True,blank=True)
    tipos=((1,'Amistoso'),)
    tipo_partido=models.SmallIntegerField(choices=tipos)
    resultado=models.CharField('Resultado',max_length=30,null=True,blank=True)
    estados = ((1, 'No iniciado'), (2, 'En proceso'), (3, 'Finalizado'))
    estado_partido = models.SmallIntegerField(choices=estados)
    cancha=models.ForeignKey(Cancha)
    local=models.ForeignKey(Equipo,related_name='equipo_1',null=True)
    visitante=models.ForeignKey(Equipo,related_name='equipo_2',null=True)
    class Meta:
        db_table='partido'
    def __str__(self):
        """return "%s %s %s %s %s" % (self.fecha_partido,self.hora_inicio,self.hora_fin,
                                self.resultado,self.estado_partido)
        """
        return "%s %s" % (self.id,self.fecha_partido)


class EventoPartido(models.Model):
    partido=models.ForeignKey(Partido)
    eventos=((1,'Marcacion del gol'),(2,'Falta'),(3,'Tarjeta amarilla'),
             (4,'Tarjeta azul'),(5,'Tarjeta roja'),(6,'Cambio de jugador'))
    tipo_evento=models.SmallIntegerField(choices=eventos)
    hora_evento=models.TimeField()
    jugador=models.ForeignKey(User)
    class Meta:
        db_table='eventos_partido'
    def __str__(self):
        return "%s %s %s" % (self.partido,self.tipo_evento,self.hora_evento)


class Torneo(models.Model):
    t_torneo=((1,'T.relampago'),(2,'Campeonato'))
    tipo_torneo=models.SmallIntegerField(choices=t_torneo,null=True)
    nombre_torneo=models.CharField('Nombre torneo',max_length=30)
    fecha_inicio = models.DateField()
    fecha_final = models.DateField()
    premio=models.TextField('Premios',max_length=100)
    estados=((1,'No iniciado'),(2,'En proceso'),(3,'Octavos de final'),(4,'Cuartos de final'),
             (5, 'Semifinales'),(6,'Finales'),(7,'Finalizado'))
    estado_torneo=models.SmallIntegerField(choices=estados)
    class Meta:
        db_table='torneo'
    def __str__(self):
        return "%s " % (self.nombre_torneo)


class Torneo_Partido(models.Model):
    torneo=models.ForeignKey(Torneo)
    partido=models.ForeignKey(Partido)
    class Meta:
        db_table='torneo_partido'
    def __str__(self):
        return "%s %s " % (self.torneo,self.partido)



class Reserva(models.Model):
    fecha_reserva=models.DateField()
    hora_inicio=models.TimeField()
    hora_final = models.TimeField()
    cancha=models.ForeignKey(Cancha)
    usuario=models.ForeignKey(User)
    abono=models.DecimalField(max_digits=6,decimal_places=2)
    estados=((1,'Reservado'),(2,'Disponible'))
    estado_reserva=models.SmallIntegerField(choices=estados)

    class Meta:
        db_table='reserva'
        unique_together = ('hora_inicio', 'cancha')

    def __str__(self):
        return "%s %s %s %s %s %s %s" % (self.fecha_reserva,self.hora_inicio,
                                         self.hora_final,self.cancha,self.usuario,
                                         self.abono,self.estado_reserva)

templates/partido/partido_detalle.html
{% extends 'base/base.html' %}
{% block title %}Detalle partido{% endblock %}
{% block fondopantalla %}{% endblock %}
{% block  content%}
<div class="panel panel-primary" align="center">
    <h3>DETALLE PARTIDO :  {{ detalle_partido.id}}</h3>
</div>
<div class="table-responsive">
    <table class="table table-hover">
        <tbody>
            <tr>
                <td>FECHA DEL PARTIDO</td>
                <td>{{ detalle_partido.fecha_partido}}</td>
            </tr>
            <tr>
                <td>ESTADO DEL PARTIDO</td>
                <td>{{ detalle_partido.get_estado_partido_display}}</td>
            </tr>
            <tr>
                <td>HORA DE INICIO</td>
                <td>{{ detalle_partido.hora_inicio}}</td>
            </tr>
            <tr>
                <td>HORA DE FINALIZACION</td>
                <td>{{ detalle_partido.hora_fin}}</td>
            </tr>
            <tr>
                <td>TIPO DE PARTIDO</td>
                <td>{{ detalle_partido.get_tipo_partido_display}}</td>
            </tr>
                <td>RESULTADO</td>
                <td>{{ detalle_partido.resultado}}</td>
            </tr>
                <td>CANCHA</td>
                <td>{{ detalle_partido.cancha.nombre_cancha}}</td>
            </tr>
                <td>EQUIPO LOCAL</td>
                <td>{{ detalle_partido.local.nombre_equipo}}</td>
            </tr>
                <td>EQUIPO VISITANTE</td>
                <td>{{ detalle_partido.visitante.nombre_equipo}}</td>
            </tr>
        </tbody>
    </table>
    <a href="{% url 'espicourts:partidos_listar' %}" button class="btn btn-success"> Listar Partidos</a>
</div>
{% endblock %}

templates/partido/partido_eliminar.html
{% extends 'base/base.html' %}
{% block title %}Eliminar partido{% endblock %}
{% block fondopantalla %}{% endblock %}
{% block content %}
<div class="panel panel-primary" align="center">
    <h3>¿Desea eliminar {{cancha.nombre_cancha }}?</h3>
</div>
<div class="form-horizontal">
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-success ">Si, eliminar</button>
        <a href="{% url 'espicourts:canchas_listar' %}" button class="btn btn-danger">Cancelar</a>
    </form>
</div>
{% endblock %}

templates/partido/partido_form.html
{% extends 'base/base.html' %}
{% block title %}Partidos{% endblock %}
{% block fondopantalla %}{% endblock %}
{% block content %}
<div class="panel panel-primary" align="center">
    <h3>PARTIDOS</h3>
</div>
<div class="form-horizontal">
    <form method="post">
        {% csrf_token %}
       {{ partido_form.as_p }}
        <br>
        <button type="submit" class="btn btn-primary ">Guardar</button>
        <a href="{% url 'espicourts:partidos_listar' %}" button class="btn btn-success"> Listar Partidos</a>
    </form>
</div>
{% endblock %}

templates/partido/partido_listar.html
{% extends 'base/base.html' %}
{% block title %}Listar partidos{% endblock %}
{% block fondopantalla %}{% endblock %}
{% block  content%}
<div class="panel panel-primary" align="center">
    <h3>PARTIDOS</h3>
</div>
<a class="btn btn-primary " href="{% url 'espicourts:partidos_crear' %}" >Registrar Partido</a>
</p>
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>Fecha Programada</th>
                <th>Hora de inicio </th>
                <th>Estado del partido </th>
            </tr>
        </thead>
        <tbody>
            {% for c in partidos%}
            <tr>
                <td>{{ c.id }}</td>
                <td>{{ c.fecha_partido}}</td>
                <td>{{ c.hora_inicio}}</td>
                <td>{{ c.get_estado_partido_display}}</td>
                <td>
                     <a href="{% url 'espicourts:partidos_detalle' c.id %}" button class="btn btn-success"> Detalle</a>
                </td>
                <td>
                     <a href="{% url 'espicourts:partidos_actualizar' c.id %}" button class="btn btn-primary"> Actualizar</a>
                </td>
                <td>
                     <a href="{% url 'espicourts:partidos_eliminar' c.id %}" button class="btn btn-danger"> Eliminar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock%}